#168050017 Add Search Functionality
andela/technites-bn-backend pull request #44
Opened 2019-09-25 22:08 UTC by TgeeT

#### What does this PR do?
Adds search functionality
#### Description of Task to be completed?
- Add endpoint to search the requests table  by a keyword or by bate
#### How should this be manually tested?
- git clone this repo and check out to `ft-add-request-search-functionality-168050017`
- run `npm i` to install all the dependencies
- run the application with `npm run dev`
- login a user in the system
- send a GET request to `/api/v1/requests/search?query`
     * In the query options either use:
         ` key_word , afterDate, beforeDate` as search options
#### Images
![image](https://user-images.githubusercontent.com/45405036/65643291-a7fd0480-dff1-11e9-9a23-f0923bcce1cf.png)

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168050017](https://www.pivotaltracker.com/story/show/168050017)
#### What are the relevant Github Issues?
#### Screenshots (if appropriate)

#### Questions:
N/A

2019-09-26 09:01 UTC, Jordybastien approved these changes
Good work Titus

2019-09-26 09:02 UTC, Jordybastien approved these changes
Good work @TgeeT, However if you could work on the issue that is decreasing our coverage that would be great

2019-09-26 09:49 UTC, TgeeT commented
@Jordybastien, I really appreciate the feedback, I have worked on it and it is now fine

2019-09-26 12:41 UTC, amilykassim requested changes
The functionality is working perfectly, however there 2 main issues : 
1)  when querying the data before
the current date and it is ending upbringing the data that is after the current date instead of the ones before the current date.

2) When querying the data against the range of dates it is indicating that there are no data in that range even if the data exist.

Otherwise, Great work, Kudos to you Titus, the search is awesome!!

2019-09-26 12:48 UTC, TgeeT commented
@amilykassim I have fixed the same, it was a matter of logic flow, it is now working appropriately

2019-09-26 13:23 UTC, didasmbalanya approved these changes

2019-09-26 13:23 UTC, didasmbalanya commented on src/routes/index.js
>  import RequestRoute from './RequestRoutes';
request route has been imported twice

2019-09-27 08:15 UTC, amilykassim approved these changes

2019-09-27 08:21 UTC, Paulvitalis200 approved these changes

2019-09-27 08:23 UTC, merged