#168977619 Update README file and create a Postman Collection
andela/technites-bn-backend pull request #70
Opened 2019-10-14 12:43 UTC by TgeeT

#### What does this PR do?
- Update the readme, adding a postman collection
#### Description of Task to be completed?
- update the README.md file
- create a postman collection
#### How should this be manually tested?
- open the reaad me file and see the updated readme file
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[ #168977619](https://www.pivotaltracker.com/story/show/168977619)
#### What are the relevant Github Issues?
N/A
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2019-10-14 15:01 UTC, Jordybastien approved these changes

2019-10-14 15:03 UTC, Jordybastien requested changes
Why is the coverage dropping

2019-10-14 15:16 UTC, TgeeT commented
Actually I was also wondering, please help me identify the uncovered line in the read me and as well let me know how I can cover it,... make it ASK feedback

2019-10-16 13:29 UTC, mucyomiller approved these changes
LGTM

2019-10-16 13:34 UTC, merged